name: bragi
namespace: production
component: frontend
tier: public

image:
  repository: asia-docker.pkg.dev/iar-motor-claims/bragi
  tag: latest

containerPort: 80
nginxWritableDirs: true

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

startupProbe:
  httpGet:
    path: /
    port: 80
livenessProbe:
  httpGet:
    path: /
    port: 80
readinessProbe:
  httpGet:
    path: /
    port: 80

httproute:
  gatewayName: production-iarservices-gateway
  hostnames:
    - "modules.iarservices.in"
